#!/bin/bash
ssh -i ~/.ssh/220rsa.pem ec2-user@ec2-54-163-7-4.compute-1.amazonaws.com -y "sudo yum -y update; sudo yum install java-17-amazon-corretto.x86_64 -y;" & 
scp -i ~/.ssh/220rsa.pem -r ~/Courses/220/final-project/MMSaboMinecraftServer/.server-data ec2-user@ec2-54-163-7-4.compute-1.amazonaws.com:
